"""add api football ids

Revision ID: 2a6259d0a1e9
Revises: 
Create Date: 2026-09-01 21:48:53.222313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a6259d0a1e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitions', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'competitions', ['api_football_id'])
    op.add_column('matches', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'matches', ['api_football_id'])
    op.add_column('players', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'players', ['api_football_id'])
    op.add_column('teams', sa.Column('api_football_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'teams', ['api_football_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teams', type_='unique')
    op.drop_column('teams', 'api_football_id')
    op.drop_constraint(None, 'players', type_='unique')
    op.drop_column('players', 'api_football_id')
    op.drop_constraint(None, 'matches', type_='unique')
    op.drop_column('matches', 'api_football_id')
    op.drop_constraint(None, 'competitions', type_='unique')
    op.drop_column('competitions', 'api_football_id')
    # ### end Alembic commands ###
